services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: finance-app

    volumes:
      - .:/var/www

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    working_dir: /var/www

    command: php artisan serve --host=0.0.0.0

  mysql:
    image: mysql:8.0

    container_name: finance-mysql

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_db

    volumes:
      - mysql_data:/var/lib/mysql

  vite:
    image: node:22

    container_name: finance-vite

    working_dir: /var/www

    volumes:
      - .:/var/www

    ports:
      - "5173:5173"

    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
