import {
    Banknote,
    Car,
    House,
    Salad,
    ShoppingBag,
    Wallet,
    Wifi,
    Briefcase,
    CreditCard,
    ShoppingCart,
    HeartPulse,
    Gamepad2,
    Smartphone,
    PiggyBank,
    UtensilsCrossed,
    Plane,
    RefreshCw,
} from "lucide-react";

export const ConfigIcon = {
    Wallet: Wallet,
    Banknote: Banknote,
    Salad: Salad,
    Car: Car,
    ShoppingBag: ShoppingBag,
    House: House,
    Wifi: Wifi,
    Briefcase: Briefcase,
    CreditCard: CreditCard,
    ShoppingCart: ShoppingCart,
    HeartPulse: HeartPulse,
    Gamepad2: Gamepad2,
    Smartphone: Smartphone,
    PiggyBank: PiggyBank,
    UtensilsCrossed: UtensilsCrossed,
    Plane: Plane,
    RefreshCw: RefreshCw,
};
